services:
  ansible:
    container_name: ansible
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - semaphore_ssh_keys:/root
      - /docker_shared_data/Ansible_Playbooks:/playBooks
      - semaphore_config:/config
    ports:
      - 3000:3000 
    environment:
      - SEMAPHORE_DB_TYPE=1
      - SEMAPHORE_DB_HOSTNAME=ansible-sql:3306
      - SEMAPHORE_DB_USER=semaphore
      - SEMAPHORE_DB_PASS=semaphore
      - SEMAPHORE_DB_NAME=semaphore
      - SEMAPHORE_PLAYBOOK_PATH=/playBooks
      - SEMAPHORE_UI_USERNAME=admin
      - SEMAPHORE_UI_EMAIL=admin@admin.com
      - SEMAPHORE_UI_NAME=admin
      - SEMAPHORE_UI_PASSWORD=changeme
      - SSH_KEY_PASSPHRASE=changeme
      
  ansible-sql:
    container_name: ansible-sql
    restart: always
    #ports:
    #  - 3306:3306
    image: mysql:8.0
    hostname: mysql
    volumes:
      - ansible_db:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: semaphore
      MYSQL_USER: semaphore
      MYSQL_PASSWORD: semaphore
      MYSQL_ROOT_PASSWORD: semaphore
        
volumes:
  semaphore_config:
  semaphore_playbooks:
  semaphore_ssh_keys:
  ansible_db:
