services:
  ansible:
    container_name: ansible
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - semaphore_ssh_keys:/root
      - playbooks:/playBooks
      - semaphore_config:/config
    ports:
      - "${SEMAPHORE_UI_PORT}:3000" 
    env_file: .env
        
  ansible-sql:
    container_name: ansible-sql
    restart: always
    image: mysql:8.0
    hostname: mysql
    volumes:
      - ansible_db:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: ${SEMAPHORE_DB_NAME}
      MYSQL_USER: ${SEMAPHORE_DB_USER}
      MYSQL_PASSWORD: ${SEMAPHORE_DB_PASS}
      MYSQL_ROOT_PASSWORD: ${SEMAPHORE_DB_ROOT_PASS}

        
volumes:
  semaphore_config:
  semaphore_playbooks:
  semaphore_ssh_keys:
  ansible_db:
  playbooks:
